---

- src: geerlingguy.docker
  version: 6.1.0

- src: git+https://gitlab.com/etke.cc/roles/swap
  version: 843a0222b76a5ec361b35f31bf4dc872b6d7d54e

- src: git+https://gitlab.com/etke.cc/roles/ssh
  version: 237adf859f9270db8a60e720bc4a58164806644e

- src: git+https://gitlab.com/etke.cc/roles/fail2ban
  version: 09886730e8d3c061f22d1da4a542899063f97f0a

- src: git+https://github.com/devture/com.devture.ansible.role.docker_sdk_for_python.git
  version: 129c8590e106b83e6f4c259649a613c6279e937a

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_help.git
  version: c1f40e82b4d6b072b6f0e885239322bdaaaf554f

- src: git+https://github.com/devture/com.devture.ansible.role.systemd_docker_base.git
  version: 327d2e17f5189ac2480d6012f58cf64a2b46efba

- src: git+https://github.com/devture/com.devture.ansible.role.timesync.git
  version: 3d5bb2976815958cdce3f368fa34fb51554f899b

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_state_preserver.git
  version: ff2fd42e1c1a9e28e3312bbd725395f9c2fc7f16

- src: git+https://github.com/devture/com.devture.ansible.role.postgres.git
  version: 38764398bf82b06a1736c3bfedc71dfd229e4b52

- src: git+https://github.com/devture/com.devture.ansible.role.postgres_backup.git
  version: 8e9ec48a09284c84704d7a2dce17da35f181574d

- src: git+https://github.com/devture/com.devture.ansible.role.container_socket_proxy.git
  version: v0.1.1-1

- src: git+https://github.com/devture/com.devture.ansible.role.traefik.git
  version: v2.9.9-0

- src: git+https://github.com/devture/com.devture.ansible.role.systemd_service_manager.git
  version: 6ccb88ac5fc27e1e70afcd48278ade4b564a9096

- src: git+https://github.com/devture/com.devture.ansible.role.playbook_runtime_messages.git
  version: 9b4b088c62b528b73a9a7c93d3109b091dd42ec6

- src: git+https://github.com/devture/com.devture.ansible.role.woodpecker_ci_server.git
  version: v0.15.7-2

- src: git+https://github.com/devture/com.devture.ansible.role.woodpecker_ci_agent.git
  version: v0.15.7-1

- src: git+https://gitlab.com/etke.cc/roles/miniflux.git
  version: v2.0.43-2

- src: git+https://gitlab.com/etke.cc/roles/grafana.git
  version: v9.4.7-0

- src: git+https://gitlab.com/etke.cc/roles/radicale.git
  version: v3.1.8.1-2

- src: git+https://gitlab.com/etke.cc/roles/uptime_kuma.git
  version: v1.21.0-0

- src: git+https://gitlab.com/etke.cc/roles/redis.git
  version: v7.0.10-0

- src: git+https://gitlab.com/etke.cc/roles/prometheus_node_exporter.git
  version: v1.5.0-7

- src: git+https://gitlab.com/etke.cc/roles/prometheus_blackbox_exporter.git
  version: v0.23.0-3

- src: git+https://gitlab.com/etke.cc/roles/redmine.git
  version: v5.0.5-1

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-aux.git
  name: aux
  version: v1.0.0-0

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-collabora-online.git
  name: collabora_online
  version: v22.05.12.1.1-0

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry.git
  name: docker_registry
  version: v2.8.1-1

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry-browser.git
  name: docker_registry_browser
  version: v1.6.0-0

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-docker-registry-purger.git
  name: docker_registry_purger
  version: v1.0.0-0

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-focalboard.git
  name: focalboard
  version: v7.8.0-0

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-gitea.git
  name: gitea
  version: v1.19.0-0

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-nextcloud.git
  name: nextcloud
  version: v26.0.0-0

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-peertube.git
  name: peertube
  version: v5.1.0-0

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-prometheus.git
  name: prometheus
  version: v2.43.0-0

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-syncthing.git
  name: syncthing
  version: v1.23.2-0

- src: git+https://github.com/mother-of-all-self-hosting/ansible-role-vaultwarden.git
  name: vaultwarden
  version: v1.27.0-2

- src: git+https://github.com/moan0s/hubsite.git
  name: hubsite
  version: da6fed398a9dd0761db941cb903b53277c341cc6

- src: git+https://github.com/moan0s/role-firezone.git
  name: firezone
  version: 9916b11161b3cdf3485c6b3c475573fc90cd1823
